global:
  scrape_interval:     15s # как часто собирать данные
  evaluation_interval: 15s # таймаут на запрос

scrape_configs:
  - job_name: 'myapp'
    metrics_path: /sdelki/actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8089']