version: '3'


services:
  redis-node-1:
    image: redis:latest
    ports:
      - 7000:7000
    hostname: redis-node-1
    volumes:
      - ./7000:/redis
    command: redis-server /redis/redis.conf
  redis-node-2:
    image: redis:latest
    ports:
      - 7001:7001
    hostname: redis-node-2
    volumes:
      - ./7001:/redis
    command: redis-server /redis/redis.conf

  redis-node-3:
    image: redis:latest
    ports:
      - 7002:7002
    hostname: redis-node-3
    volumes:
      - ./7002:/redis
    command: redis-server /redis/redis.conf

  
  redis-cluster-creator:
    image: redis:latest
    ports:
      - 6999:6999
    command: redis-cli -p 7000 --cluster create redis-node-1:7000 redis-node-2:7001 redis-node-3:7002 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3

  
  redis-insight:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis-cluster-creator
